# Generated by Django 4.2.15 on 2024-09-08 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_diploma', models.BooleanField(default=True)),
                ('branch', models.CharField(blank=True, choices=[('entc', 'ENTC'), ('civil', 'Civil'), ('mech', 'Mechanical')], max_length=50)),
                ('pursuing_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('books_obtained', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
