# Generated by Django 4.2.15 on 2024-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('entc', 'ENTC'), ('civil', 'Civil'), ('mech', 'Mechanical'), ('comp', 'Computer'), ('entc', 'ENTC'), ('civil', 'Civil'), ('mech', 'Mechanical')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='education_type',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('degree', 'Degree')], default='diploma', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pursuing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_image',
            field=models.ImageField(default='student_info/user.jpg', upload_to='student_info'),
        ),
    ]
