# Generated by Django 4.2.15 on 2024-09-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_branch_remove_user_education_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('phone', models.CharField(max_length=12)),
                ('education_type', models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=10)),
                ('select_branch', models.CharField(choices=[('ENTC', 'ENTC'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Computer', 'Computer')], max_length=20)),
                ('pursuing_year', models.IntegerField()),
                ('books_obtained', models.TextField(blank=True, help_text='List of books obtained')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
