# Generated by Django 4.2.15 on 2024-09-30 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=35)),
                ('student_image', models.ImageField(default=None, upload_to='student_info/')),
                ('phone', models.CharField(max_length=12)),
                ('education_type', models.CharField(max_length=10)),
                ('select_branch', models.CharField(blank=True, max_length=30, null=True)),
                ('pursuing_year', models.IntegerField(default='1')),
                ('books_obtained', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_by',
            field=models.ManyToManyField(related_name='borrowed_books', through='home.Borrow', to=settings.AUTH_USER_MODEL),
        ),
    ]
