# Generated by Django 4.2.15 on 2024-09-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_students_books_obtained_students_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='pursuing_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_image',
            field=models.ImageField(upload_to='student_info'),
        ),
    ]
