# Generated by Django 4.2.15 on 2024-10-04 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_fine_paid_alter_borrow_borrowed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
