# Generated by Django 4.2.15 on 2024-09-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_students_email_alter_students_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='books_obtained',
        ),
    ]
