# Generated by Django 4.2.15 on 2024-09-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_students_books_obtained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(blank=True, choices=[('entc', 'ENTC'), ('civil', 'Civil'), ('mech', 'Mechanical'), ('comp', 'Computer'), ('entc', 'ENTC'), ('civil', 'Civil'), ('mech', 'Mechanical')], max_length=10),
        ),
    ]
