# Generated by Django 4.2.15 on 2024-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_students_email_alter_students_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
