# Generated by Django 4.2.15 on 2024-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='pursuing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
