# Generated by Django 4.2.15 on 2024-09-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_students_pursuing_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
