# Generated by Django 4.2.15 on 2024-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('all', 'All'), ('computer', 'Computer'), ('entc', 'ENTC'), ('mech', 'Mech'), ('civil', 'Civil')], default='all', max_length=20, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='readonline/')),
                ('book_pdf', models.FileField(upload_to='readonline/pdfs/')),
            ],
        ),
    ]
