# Generated by Django 4.2.15 on 2024-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='education_type',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('degree', 'Degree')], default='diploma', max_length=7, null=True),
        ),
    ]
