# Generated by Django 4.2.15 on 2024-12-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_readonline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readonline',
            old_name='book_image',
            new_name='pdf_image',
        ),
    ]
