# Generated by Django 4.2.15 on 2024-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_book_image_readonline_pdf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readonline',
            name='book_pdf',
            field=models.FileField(upload_to='readonline/'),
        ),
    ]
