# Generated by Django 4.2.15 on 2024-12-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_readonline_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readonline',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='readonline/'),
        ),
    ]
