# Generated by Django 4.2.15 on 2024-09-10 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_remove_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='books_obtained',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='education_type',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('degree', 'Degree')], default='diploma', max_length=7),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='pursuing_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_info'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
