# Generated by Django 4.2.15 on 2024-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_students_books_obtained_students_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='student_email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
        migrations.AddField(
            model_name='students',
            name='student_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='pursuing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
