# Generated by Django 4.2.15 on 2024-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_email_students_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
