# Generated by Django 4.2.15 on 2024-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_students_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
