# Generated by Django 4.2.15 on 2024-09-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_students_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
