# Generated by Django 4.2.15 on 2024-12-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_studentprofile_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
