# Generated by Django 4.2.15 on 2024-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_studentprofile_books_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='pursuing_year',
            field=models.IntegerField(),
        ),
    ]
