# Generated by Django 4.2.15 on 2024-09-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_studentprofile_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='pursuing_year',
            field=models.IntegerField(default=''),
        ),
    ]
