# Generated by Django 4.2.15 on 2024-09-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_studentprofile_books_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='books_obtained',
            field=models.TextField(blank=True, null=True),
        ),
    ]
