# Generated by Django 4.2.15 on 2024-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_studentprofile_books_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='pursuing_year',
            field=models.IntegerField(default='1'),
        ),
    ]
