# Generated by Django 4.2.15 on 2024-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_studentprofile_pursuing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='select_branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
