name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger workflow on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-24.04  # Use Ubuntu runner for deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the latest code from the repository

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # Set up SSH for GitHub Actions
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}  # AWS private SSH key

    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H 52.66.255.93 >> ~/.ssh/known_hosts  # Add EC2 IP to known hosts
        chmod 644 ~/.ssh/known_hosts

    - name: SSH into EC2 and deploy
      run: |
        # ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@52.66.255.93 << 'EOF'
        # Navigate to project directory
        cd project/Django_Library  # Update with your project directory

        # Pull the latest changes from the repository
        git pull origin main

        # Activate virtual environment
        source env/bin/activate

        # Install dependencies
        pip install -r requirements.txt

        # Apply database migrations
        python manage.py makemigrations
        python manage.py migrate

        # Collect static files
        python manage.py collectstatic --no-input

        # Restart Gunicorn to apply changes
        sudo systemctl restart gunicorn

        # Restart Nginx (if required)
        sudo systemctl restart nginx
        EOF
